### ISSUE TITLE
Add high level yaml switch for automated job emails

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#147]
Might give independent switches for `variational`, `forecast`, etc... sections of YAML with default set to `False`

**Comment by jjguerrette** [comment]
This will be addressed in #202.

The email setting for all tasks is parsed here:
https://github.com/NCAR/MPAS-Workflow/blob/feature/1_pythonConfigParse/initialize/config/Task.py#L16

`Variational`, `Forecast`, and `RTPP` classes set the value of `email` to `True` by default.

Users can add the following to their scenario YAML to override the default `email` setting for `Variational`, `Forecast`, and `RTPP`, respectively:

```yaml
variational:
  job:
    defaults:
      email: False

forecast:
  job:
    defaults:
      email: False

rtpp:
  job:
    defaults:
      email: False
```
