### ISSUE TITLE
Wrong channel selection for NCDIAG AMSUA variational

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#95]
For example:
https://github.com/NCAR/MPAS-Workflow/blob/b13210ac8103f738133ff67ded1df8b129f08acf/config/ObsPlugs/variational/base/amsua_n19.yaml#L9

Previously we only assimilated a limited channel set for AMSUA instruments in PANDACArchive experiments.  We could remove some of the channels with `filters` similar to what is done in the `filtersWithBias` yamls.

**Comment by jjguerrette** [comment]
For example:
```yaml
#  Useflag check #amsua-n19
  - filter: Bounds Check
    filter variables:
    - name: brightness_temperature
      channels: *amsua_n19_channels
    test variables:
    - name: ChannelUseflagCheckRad@ObsFunction
      channels: *amsua_n19_channels
      options:
        channels: *amsua_n19_channels
        use_flag: [ -1, -1, -1, -1,  1,
                     1, -1, -1,  1, -1,
                    -1, -1, -1, -1, -1 ]
    minvalue: 1.0e-12
    action:
      name: reject
```
